version: "3.9"
services:
  web:
    build: .
    depends_on:
      - mongo
    environment:
      - HOST=http://localhost
      - PORT=3000
      - PORT_IO=3001
      - dbConnectionString=mongodb://root:password@mongo:27017/appYGO?authSource=admin
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/Users/10037963/Downloads/app
      - /Users/10037963/Downloads/app/node_modules
  mongo:
    image: mongo
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"